//----------------------------------------
// GENERATE FILE - DO NOT MODIFY BY HAND
// This code is generated by
// salpha_package translation common assist
//----------------------------------------

Map<String, String> ko = {
  "material_apptitle" : "플러터 데모",
  "home_title" : "플러터 데모 홈페이지",
  "text_times" : "요만큼 버튼을 눌렀네요:",
  "tooltip_add" : "증가",
};
