// ignore_for_file: type=lint
//----------------------------------------
// GENERATE FILE - DO NOT MODIFY BY HAND
// This code is generated by
// salpha_package translation common assist
//----------------------------------------

Map<String, String> en = {
  "material_apptitle" : "Flutter Demo",
  "home_title" : "Flutter Demo Home Page",
  "text_times" : "You have pushed the button this many times:",
  "tooltip_add" : "Increment",
};
