// ignore_for_file: type=lint
//----------------------------------------
// GENERATE FILE - DO NOT MODIFY BY HAND
// This code is generated by
// salpha_package translation common assist
//----------------------------------------

abstract interface class LocaleKeys {
  static const materialApptitle = "material_apptitle";
  static const homeTitle = "home_title";
  static const textTimes = "text_times";
  static const tooltipAdd = "tooltip_add";
}
